apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: final
spec:
  selector:
    app: employee
  ports:
    - protocol: TCP
      name: myapp-deployment
      port: 81
      targetPort: 81
  type: LoadBalancer