apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: final
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 937545311489.dkr.ecr.us-east-1.amazonaws.com/mysql:v1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql
          mountPath: /data
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
