kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
  namespace: final
  labels:
    app: final
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi #storage